# Generated by Django 5.1.1 on 2024-09-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shahid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200, verbose_name='last name')),
                ('martyrdom_location', models.CharField(max_length=200)),
                ('martyrdom_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='shohada_images')),
            ],
        ),
    ]
