# Generated by Django 5.1.1 on 2024-09-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shahid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shahid',
            name='martyrdom_date',
            field=models.DateField(),
        ),
    ]
