# Generated by Django 5.1.1 on 2024-09-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shahid', '0003_shahid_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='shahid',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='shohada_qrcodes'),
        ),
    ]
