# Generated by Django 5.1.1 on 2024-09-27 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shahid', '0007_remove_shahid_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shahid',
            name='qr_code_image',
        ),
    ]
