# Generated by Django 5.1.1 on 2024-09-27 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shahid', '0008_remove_shahid_qr_code_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shahid.shahid'),
        ),
    ]
