# Generated by Django 5.1.1 on 2024-09-27 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shahid', '0010_rename_name_shahid_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'عکس', 'verbose_name_plural': 'عکس\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='shahid',
            options={'verbose_name': 'شهید', 'verbose_name_plural': 'شهدا'},
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='shohada_images', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='image',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shahid.shahid', verbose_name='شهید'),
        ),
        migrations.AlterField(
            model_name='shahid',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='shahid',
            name='birth_location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='محل تولد'),
        ),
        migrations.AlterField(
            model_name='shahid',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='shahid',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='shahid',
            name='important_quotes',
            field=models.TextField(blank=True, null=True, verbose_name='نقل\u200cقول\u200cهای مهم'),
        ),
        migrations.AlterField(
            model_name='shahid',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='shahid',
            name='martyrdom_date',
            field=models.DateField(verbose_name='تاریخ شهادت'),
        ),
        migrations.AlterField(
            model_name='shahid',
            name='martyrdom_location',
            field=models.CharField(max_length=200, verbose_name='محل شهادت'),
        ),
        migrations.AlterField(
            model_name='shahid',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='شناسه'),
        ),
        migrations.AlterField(
            model_name='shahid',
            name='will',
            field=models.TextField(blank=True, null=True, verbose_name='وصیت\u200cنامه'),
        ),
    ]
