# Generated by Django 5.1.1 on 2024-09-27 10:34

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shahid', '0011_alter_image_options_alter_shahid_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shahid',
            name='birth_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='shahid',
            name='martyrdom_date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ شهادت'),
        ),
    ]
